### ISSUE TITLE
Error launching CLI Wallet

### ISSUE THREAD

**Issue by LeChatNoir69** [karlsen-network/node-karlsen-wallet-cli#2]
Hi,

When launching CLI Wallet, here is the error :

~/node-karlsen-wallet-cli$ node karlsen-wallet
/home/lechat/node-karlsen-wallet-cli/karlsen-wallet.js:48
			errorCB?.(count)
			        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

Thank you

**Comment by lemois-1337** [comment]
@LeChatNoir69 How did you installed the dependencies? And could you post Node.js and npm version?

```
node --version
npm --version
```

And did you tried the published version in npm registry as well?

**Comment by LeChatNoir69** [comment]
Just installed as indicated :

git clone https://github.com/karlsen-network/node-karlsen-wallet-cli
cd node-karlsen-wallet-cli
npm install

Tried the other method too but same error.

lechat@mainnode:~$ node --version
v12.22.9
lechat@mainnode:~$ npm --version
8.5.1

**Comment by lemois-1337** [comment]
Minimum required node version is 14, could you please re-run it on a newer one?

**Comment by LeChatNoir69** [comment]
Just updated node version and it works. Thank you !
